### ISSUE TITLE
Stream json content includes empty metadata element

### ISSUE THREAD

**Issue by jrshust** [Calysto/metakernel#100]
Why does the the stream message contain an additional metadata field that is just set to an empty dict()? (e.g. https://github.com/Calysto/metakernel/blob/master/metakernel/_metakernel.py#L605).

I implemented the jupyter message protocol in my project and followed the spec here (https://jupyter-client.readthedocs.io/en/latest/messaging.html#streams-stdout-stderr-etc) which doesn't show a metadata dictionary field for stream messages. The reason this is a problem is that it breaks JSON serialization in my app; I would rather not add a random optional field that is not specified in the jupyter spec.

I would like to create a PR to remove it but want to understand why it is there now since so many projects depend on the metakernel. Thank you.

**Comment by dsblank** [comment]
That is likely a leftover from a previous version of Jupyter. It looks like it was there from the beginning of metakernel. PR would be welcome, and we can test on a few other kernels to make sure there is no issue.

**Comment by dsblank** [comment]
Should be fixed in version 0.13.5.
