### ISSUE TITLE
! pwd - shell magic prints pwd three times

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#101]
Something is wrong with some shell commands that repeat their output:

``` shell
! pwd
! ls
! echo hello
```

Other commands don't:

``` shell
! cd /tmp
```

**Comment by vilhelmen** [comment]
Not that I know the cause, but in working with the bash kernel I've found that it duplicates whatever the last non-whitespace line of output is.

**Comment by dsblank** [comment]
I believe that this is now fixed.
