### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by anntzer** [Calysto/metakernel#106]
Would be nice if releases were git-tagged, so that they show up in https://github.com/Calysto/metakernel/releases and https://github.com/Calysto/metakernel/tags

**Comment by dsblank** [comment]
Yes. I tried briefly to do that last week but failed. Need to figure that out.

**Comment by blink1073** [comment]
https://github.com/Calysto/metakernel/commit/83adb97ef7736ab5b3c0760df0be0bb2a9876d91 adds a tags push to our release script.

**Comment by dsblank** [comment]
That was the magic needed... thanks!

**Comment by blink1073** [comment]
![magic](https://cloud.githubusercontent.com/assets/2096628/18126424/b18d19f6-6f40-11e6-94a0-d9ae3dac91d3.gif)

**Comment by anntzer** [comment]
FWIW a tag for 0.14 is missing.
