### ISSUE TITLE
Pluggable completion escaper

### ISSUE THREAD

**Issue by anntzer** [Calysto/metakernel#107]
#36 introduced escaping of paths that contain spaces using backslashes on Linux (https://github.com/Calysto/metakernel/blob/ab89fdf5fc36d81fea36bf47cb98e4006f98de48/metakernel/parser.py#L273).  Unfortunately such a completion is not valid for the MATLAB kernel, which requires instead single-quoting of the path.

Perhaps this escaper could be made pluggable at the kernel level?

**Comment by dsblank** [comment]
Does #110 take care of this issue?

**Comment by anntzer** [comment]
Yes.
