### ISSUE TITLE
Pluggable magic prefix

### ISSUE THREAD

**Issue by anntzer** [Calysto/metakernel#108]
The `%` prefix for magics is not very nice for MATLAB as it is also the syntax for comments there.  It may make sense to allow kernels to specify their magic prefix, e.g. the MATLAB kernel could pick `#`.

**Comment by blink1073** [comment]
This is available as a class-level attribute: https://github.com/Calysto/metakernel/blob/a46a251d77e16054de11dd7461f73bf525f353bc/metakernel/_metakernel.py#L71

**Comment by anntzer** [comment]
Thanks.  Is this documented somewhere?

**Comment by dsblank** [comment]
There are probably a couple of other places that the % slipped in as a hardcoded item. We should fix those.

Documentation could be added in the docstrings, which would then appear here:
http://calysto.github.io/metakernel/source/api.html#metakernel.MetaKernel

But, not, we don't have much developer documentation yet.

**Comment by dsblank** [comment]
lsmagic hard coded % fixed in 2146bd6

**Comment by dsblank** [comment]
Found some additional cases of hard-coded %: 635eb64

Other than adding developer documentation (for everything!) I think this issue can be closed.
