### ISSUE TITLE
jupyterlab doesn't render HTML from metakernel

### ISSUE THREAD

**Issue by jld23** [Calysto/metakernel#111]
I have a kernel ([sas_kernel](https://github.com/sassoftware/sas_kernel)) based on metakernel and all the HTML results are swallowed by the notebook using Jupyterlab.
The same code works using the native Python kernel hence opening the issue here instead of jupyterlab
![jupyterlabissue](https://cloud.githubusercontent.com/assets/3160523/18684821/9f1848dc-7f43-11e6-89d5-29508e15f0ba.PNG)

**Comment by dsblank** [comment]
We had to do some trickery because the display infrastructure is different. Looks like we need to start playing with JupyterLab with our kernels...

**Comment by jld23** [comment]
Let me know how I can help.

**Comment by dsblank** [comment]
@jld23 That would be great. The issue is probably in this code:

https://github.com/Calysto/metakernel/blob/master/metakernel/_metakernel.py#L589-L605

This is the bit of code that handles routing rich media items to the right place.

**Comment by blink1073** [comment]
I just tried this with the latest JupyterLab master and the Calysto Bash kernel:

<img width="376" alt="screen shot 2016-09-21 at 10 49 18 pm" src="https://cloud.githubusercontent.com/assets/2096628/18735669/a96c09bc-804d-11e6-8455-eb3da1ebd98a.png">

**Comment by dsblank** [comment]
@jld23 Did you track down your issue?

**Comment by jld23** [comment]
@dsblank, I did track it down it was in line 582. I noticed some line differences and checked the version and it seems between 13.6 and 14.0 this was addressed. After I upgraded to 14, things are working as expected.  
Closing issue. 

Thanks,
Jared

**Comment by dsblank** [comment]
Thanks for the update!
