### ISSUE TITLE
Problems with jupyterhub

### ISSUE THREAD

**Issue by mmatera** [Calysto/metakernel#113]
For some reason, processmetakernel dies when the kernel is launched from jupyterhub. It seems  happen both in with the octave as well as with the iwolfram kernel that I am developing. Is there any way to fix this behavior?

**Comment by blink1073** [comment]
Hi @mmatera, what do you get for the following while on hub?

<img width="434" alt="screen shot 2016-11-10 at 9 35 09 am" src="https://cloud.githubusercontent.com/assets/2096628/20187420/0e1131e2-a729-11e6-8e9c-32d03d89d1a3.png">

**Comment by mmatera** [comment]
With these commands (from the python interpreter) I get 

 b'GNU Octave, version 3.8.1\nCopyright (C) 2014 John W. Eaton and others.\nThis is free software; see the source code for copying conditions.\nThere is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or\nFITNESS FOR A PARTICULAR PURPOSE.\n\nOctave was configured for "x86_64-pc-linux-gnu".\n\nAdditional information about Octave is available at http://www.octave.org.\n\nPlease contribute if you find this software useful.\nFor more information, visit http://www.octave.org/get-involved.html\n\nRead http://www.octave.org/bugs.html to learn how to submit bug reports.\n'

**Comment by blink1073** [comment]
Does the following work?

```python
from metakernel.replwrap import bash
bash().run_command('ls')
```

**Comment by mmatera** [comment]
This also seems to work:
![res](https://cloud.githubusercontent.com/assets/2862288/20211549/dce3d79a-a7dd-11e6-89a1-3a79f866e967.png)

**Comment by mmatera** [comment]
And this also works:

from metakernel.replwrap import bash
bash().run_command('echo "bla"; sleep 2; echo "bla"')

out[1]:  'bla\r\nbla\r\n'

**Comment by blink1073** [comment]
Do you have access to any terminal output from the JupyterHub instance, or is there any error message on the front end?

**Comment by mmatera** [comment]
Finally I think I have found the root of the problem: metakernel seems to crash in jupyterhub when the executable which process the inputs uses the Gnu readline library.

**Comment by blink1073** [comment]
Hi @mmatera, sorry, I lost track of this.  Does this work for you?

```ipython
In [1]: from octave_kernel.kernel import OctaveEngine

In [2]: OctaveEngine().eval('disp("hello")')
Out[2]: 'hello\r\n'
```

**Comment by mmatera** [comment]
The problem was I was using a version of octave compiled with the readline library. When I changed it for the standard version it started to work again.

**Comment by blink1073** [comment]
Glad you got sorted, and thank you for following up with the fix.
