### ISSUE TITLE
missing ipykernel dep

### ISSUE THREAD

**Issue by fabiommendes** [Calysto/metakernel#115]
It seems that metakernel requires ipykernel but it is not being installed using pip

**Comment by dsblank** [comment]
If you install ipykernel manually, then everything works?

**Comment by blink1073** [comment]
@dsblank, our dependencies would be a lot cleaner if we start depending on IPython/Jupyter 4.0 packages directly, what do you say?

**Comment by dsblank** [comment]
Sounds good to me!
