### ISSUE TITLE
timeouts 

### ISSUE THREAD

**Issue by erigler-usgs** [Calysto/metakernel#116]
I'm using octave_kernel, but I'm now certain there is no (easy) way to fix my problem without changing process_metakernel in Calysto. When I run a command that takes a long time to return a prompt, or any kind of text for that matter, I get the dreaded pexpect 30-second default timeout. 

A "fix" for this was committed almost a year ago (8b4429ffafbc201b4e8af5bcbe00ac647a8176f0). However, the critical part (`timeout=None`) was reverted barely a week later (`timeout=-1`, d9c975538b30061a7a6a62bedc4e8b2fc4447f88), along with changes to pexpect itself that changed the behavior of `timeout=None` to just use the default timeout of 30 seconds.

I have to admit I understand very little of this, but I suspect the author(s) of these changes consider the original bug to be only an issue when there is a continuous stream of output from a long-running process. I would ask that they consider the case when a process runs quietly for a long time. I realize this is probably an edge case, but at least for the kind of work I do with Octave, it is not all that uncommon.

Maybe there is a "fix" that at least allows the child kernel (octave_kernel in this case) to specify the timeout. As it stands, my only options are to manually modify the pexpect files, or to modify my Octave code to spit out a stream of output that prevents the timeout from triggering. Neither of these are very satisfying.

**Comment by blink1073** [comment]
What if we added a `%timeout` magic to process kernels where you can specify the timeout?

**Comment by erigler-usgs** [comment]
If I understand you, this (%timeout magic) could be set for any kernel based on metakernel as a run-time configuration. Is that about right?

Sounds much better than what I had in mind, which would have still required modification of the child kernel (e.g., octave_kernel) any time a change was required. I'm not sure how much I can help with coding it up, but I'd be very happy to help test.

**Comment by dsblank** [comment]
Maybe instead of another special magic, this could be part of a "kernel config" magic. We could use  %config, or %meta ...

**Comment by blink1073** [comment]
I'd be fine with `%config`, as long as we only affect the settings explicitly being set (not have to specify all options each time), and have an easy way to reset.

**Comment by blink1073** [comment]
I've been meaning to update the semantics of the `%plot` magic similarly, I will try and do both this weekend.

**Comment by blink1073** [comment]
I was in the process of adding this, and realized we should not have a timeout at all.  I am going to look into using pexpect 4.2 as a dependency, which has Windows support.
