### ISSUE TITLE
Display and allow interactions with widgets

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#12]
This will take a little work so that widgets will work correctly. IPython's widgets may be tied currently to their kernel.

**Comment by dsblank** [comment]
`wrapperkernels` could use widgets if this were corrected:

```python
Traceback (most recent call last):
  File "In [25]", line 1, col 1, in 'Button'
UnhandledException: Comms cannot be opened without a kernel and a comm_manager attached to that kernel.
```

**Comment by blink1073** [comment]
Is that on our end or IPython?  Can you give some example code?

**Comment by dsblank** [comment]
I think we need to do some initialization that the IPython ZMQ kernel does. Here is how to test:

```python
from IPython.html.widgets import Button
Button()
```

**Comment by blink1073** [comment]
Here's where do it: https://github.com/ipython/ipython/blob/master/IPython/kernel/zmq/ipkernel.py#L65.  I'm not sure how to handle the need for a `shell`.

**Comment by blink1073** [comment]
We might be able to use a raw `Comm` and pass `None` for `shell`:  https://github.com/ipython/ipython/blob/master/IPython/kernel/comm/comm.py#L15

**Comment by blink1073** [comment]
I took a crack at the implementation, but I'm still confused as to how to test it.  I fired up Metakernel Python and ran the code: no error, but no output.

**Comment by dsblank** [comment]
Great! I think to get it to display, some work needs to be done in `MetaKernel.Display()`... I had written that for IPython 2.0 in C#, but it was a year ago so I'll have to find it, and see if it still works. Or we can try to use IPython's handling of it... that would be easier.

**Comment by dsblank** [comment]
Here is the same code in IPython's Python:

![screenshot from 2015-01-25 08 38 58](https://cloud.githubusercontent.com/assets/168568/5891601/bf61c3f0-a46d-11e4-8c86-364afde88e62.png)

To give the button some text, use `Button(description="Click me!")`

**Comment by blink1073** [comment]
I tried also using the `shell` instantiation from `IPythonKernel`, but got nowhere fast.

**Comment by dsblank** [comment]
We are in unexplored territory here trying to use the widgets without the rest of IPython. Will probably take some deep diving to find what is missing or what assumptions we are breaking. But, I don't think it should be too much, and will be quite useful to us. After we get this working in MetaKernel Python, then we should be able to do some cool things with the rest of our kernels... widgets from Octave, etc.

**Comment by blink1073** [comment]
Perhaps we need to start an actual IPython kernel (via %kx), and funnel display calls there?

**Comment by dsblank** [comment]
Something like that... I think `%python Button()` be about the same.

**Comment by dsblank** [comment]
Oh, you said IPython kernel... yes that is a good idea.

**Comment by dsblank** [comment]
Although, we should be able to make it work inside our own. If we do it in another process, there may be some serialization issues (speed, differences in representations, etc) and socket issues (double the web sockets used?)

**Comment by blink1073** [comment]
My impression is that the %kx method is an acceptable short term solution, with help needed by the IPython devs for the proper implementation.

**Comment by dsblank** [comment]
Sounds good to me! Although our %kernel was only designed to work with MetaKernel kernels... not sure if it will work with an IPython kernel. I suspect some of the items in the constructor are required, whereas we allow nothing, indicating a subkernel.

**Comment by dsblank** [comment]
I have a version of widgets working with metakernel via 68df2bc. You were very close, just two things missing: needed to register message types with the message handler, and we needed to display them correctly. We may be able to get rid of our kernel.Display and use IPython's display directly... not sure. In any event, I use theirs to display widgets, and it worked in my brief testing:

![screenshot from 2015-01-25 22 30 59](https://cloud.githubusercontent.com/assets/168568/5895082/b9dc2608-a4e2-11e4-89fd-39407f83720e.png)

I am not sure if all of the other slick things widgets can do will work, but this should be a working foundation. Not sure how to write tests for these...

**Comment by dsblank** [comment]
(The above screen shot is the MetaKernel Python by the way. Just want to make sure it was clear that this is our kernel displaying widgets.)

**Comment by blink1073** [comment]
Awesome, but it's not *quite* working yet.  I tried this [demo](http://nbviewer.ipython.org/github/esss/ipython/blob/master/examples/Interactive%20Widgets/Using%20Interact.ipynb) and the output of interact is a series of `<IPython.core.display.HTML object>` prints.

**Comment by blink1073** [comment]
I tried a few other widgets on their own and they all work, so it's something about `interact`

**Comment by blink1073** [comment]
Actually, its `display(HTML(...))`

**Comment by blink1073** [comment]
As for testing, we can cherry pick from [here](https://github.com/ipython/ipython/blob/master/IPython/html/widgets/tests/test_interaction.py).

**Comment by dsblank** [comment]
You just need to use metakernel's display. So change:
```
from IPython.display import clear_output, display, HTML
```
to 
```
from metakernel.display import clear_output, display, HTML
```

**Comment by dsblank** [comment]
We can probably get IPython.display.display to work... not quite sure yet. Or, we could monkeypatch IPython.display when we start metakernel. Or, just use metakernel's display.

**Comment by blink1073** [comment]
HTML works with that change, but now interact prints a new output for every change...

**Comment by dsblank** [comment]
Maybe we need to insert a clear_output in metakernel's display.

**Comment by blink1073** [comment]
It seems that way.  Also, the last call in that notebook `i.widget` prints `<IPython.html.widgets.widget_box.Box object at 0x7f2ed4077c18>`.

**Comment by dsblank** [comment]
Yes, I think we need to check for Widget in kernel.Print() as well, and if it is one, display it.

**Comment by dsblank** [comment]
If we can figure out how to hook things up properly, we can use IPython's standard print and display, and we won't have to handle these objects ourselves.

**Comment by blink1073** [comment]
I'm sufficiently confusing for tonight (I tried handling Widget in kernel.Print() and failed), to be continued!

**Comment by dsblank** [comment]
Just added ability for Print to Display widgets. Although, I hope to remove these eventually and use native IPython functions for both.

Now, we need to see how we can integrate with other languages. Perhaps we will be able to use `kernel.set_variable()`, `kernel.get_variable()` for moving values back and forth between %python and kernel...

**Comment by dsblank** [comment]
Apparent breakage... looking at it...

**Comment by dsblank** [comment]
Hmmm... I don't see what is wrong... the text appears to be the same, and nothing has changed with that code:

https://github.com/ipython/ipython/commits/7ab0a492515d553091e84b370e934e6aac290c99/IPython/kernel/zmq/zmqshell.py

**Comment by dsblank** [comment]
Ok, I think I need to fix newlines reprs in print...

**Comment by dsblank** [comment]
Nevermind... stoopid brain, typo

**Comment by blink1073** [comment]
Nice work!  For some reason I can't get my work computer to recognize the MetaKernel Python kernel to try it out...

**Comment by dsblank** [comment]
I suspect that you have an old kernel in ~/.ipython/kernels/ ... or
/usr/local/share/jupyter/kernels/ ... try deleting those, and then "cd
metakernel_python; python setup.py install"

-Doug

**Comment by blink1073** [comment]
Nothing in either place

**Comment by blink1073** [comment]
Whoops:
`error: [Errno 2] No such file or directory: 'workspace/metakernel/metakernel/logo-64x64.png'`

**Comment by blink1073** [comment]
It works if I move `images` under `metakernal` and with the following change:

```diff
--- a/metakernel/utils/kernel.py
+++ b/metakernel/utils/kernel.py
@@ -8,6 +8,9 @@ def install_kernel_resources(destination, resource="metakernel", files=None):
     if files is None:
         files = ["logo-64x64.png", "logo-32x32.png"]
     for filename in files:
-        data = pkgutil.get_data(resource, filename)
+        try:
+            data = pkgutil.get_data(resource, filename)
+        except Exception:
+            data = pkgutil.get_data(resource, os.path.join('images', filename))
         with open(os.path.join(destination, filename), "wb") as fp:
             fp.write(data)
```

**Comment by dsblank** [comment]
Sounds good to me...

**Comment by blink1073** [comment]
None of the widgets are working now  :(.  The html is printing just fine, but none of the widgets are displaying.

**Comment by blink1073** [comment]
False alarm, need to clear the browser cache.  :smile:

**Comment by blink1073** [comment]
I'm not getting calls to `Display` *or* `Print` for the last line of that demo.

**Comment by dsblank** [comment]
Hmmm... it may be that we need to see if a returned value is a widget and
handle it there in `do_execute` ... other objects that have special repr
methods must be handled by IPython's wrapper around do_execute, because I
believe that a returned image would display.

**Comment by blink1073** [comment]
Fixed in 0bdb805.

**Comment by blink1073** [comment]
Fixed interact!  PR coming...

**Comment by blink1073** [comment]
I can't figure out how to handle the old `pgkutil.get_data` path anymore, and I'm just guess and checking with Travis, do you mind checking it out?

**Comment by blink1073** [comment]
Yeah, I really think we can do this just using the message spec.  I'll take a closer look tonight.

**Comment by blink1073** [comment]
Got down to the lowest level that does not call a private method (`widget._ipython_display_()`) in 96932a1.

**Comment by dsblank** [comment]
Nice clean up! So, is the only thing here broken (that we know about) is the pgkutil.get_data install issue? Were you having trouble installing in a virtual environment?

**Comment by blink1073** [comment]
I'm using a conda env. Yep, that should be the only thing.

**Comment by dsblank** [comment]
Does `pkgutil.get_data(resource, os.path.join('images', filename))` work for your setup?

**Comment by blink1073** [comment]
It does.

**Comment by dsblank** [comment]
Ok, Travis is happy, and works on my system too. I don't really understand it, but it works.

**Comment by blink1073** [comment]
Yay "standard" library!

**Comment by dsblank** [comment]
So it looks like everything appears to be working, with the only limitation that we have to use `metakernel.display.display` rather than `IPython.display.display`. Is that your understanding too?

**Comment by blink1073** [comment]
Yep.

**Comment by dsblank** [comment]
Do you think that we should:

```
import IPython.display
import metakernel.display

IPython.display.display = metakernel.display.display
```
If so, when would we do it? We'd have to make sure it was that way for any subkernel, in their env.

**Comment by dsblank** [comment]
Or perhaps IPython could rewrite `display` in a more generic way? Not sure how, though.

**Comment by blink1073** [comment]
Well, that assumes the kernel language is Python.  I still think we need a %display magic to handle this.

**Comment by blink1073** [comment]
But we *could* monkeypatch IPython display for the Python kernels using a method like [this](https://bitbucket.org/spyder-ide/spyderlib/src/814d2d4dafc02c8550bb5808ca274bf30f2f1621/spyderlib/widgets/externalshell/sitecustomize.py?at=default#cl-421).

**Comment by blink1073** [comment]
Actually, that method is for patching methods, there is probably a simpler way to override just a module-level function.

**Comment by dsblank** [comment]
> Well, that assumes the kernel language is Python. I still think we need a %display magic to handle this.

Some metakernel languages are written in Python, and could use this directly (eg, we have Scheme, Logo, Pascal, Basic, etc).

Maybe we should just leave it as is, for the time being for those languages, and MetaKernel Python.

But yes, we need some magics for the rest of the metakernel languages.

**Comment by blink1073** [comment]
Are you able to get `metakernel.display` to work right now?

**Comment by dsblank** [comment]
Yes, it worked ... at least for the things I tried.

On Tue, Jan 27, 2015 at 10:22 AM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
User error (and the stderr was not printing).  Interesting, I can now use `from IPython.display import display` and that works, does it work for you?

**Comment by blink1073** [comment]
Nevermind, `Button` worked but not the `HTML` outputs.

**Comment by dsblank** [comment]
If one can work, perhaps we can make the other work, too.

**Comment by dsblank** [comment]
> It works if I move images under metakernel and with the following change:

@blink1073 Can you check to see if you can still install and use metakernel, accessing the images? I was having some issues, and changed the setup a bit.

**Comment by blink1073** [comment]
Works for me.

**Comment by blink1073** [comment]
I was looking into `display` again, and I think it comes down to this [function](https://github.com/ipython/ipython/blob/master/IPython/core/display.py#L77) having a concept of what the current iopub socket is and writing to that instead.

**Comment by dsblank** [comment]
@blink1073 I think you are right. It is the shell instance that causes our problems, I think.

**Comment by dsblank** [comment]
I think that everything related to widgets is working. metakernel.display now has everything that IPython.display has (such as display), but with correct versions for these kernels. We still need to think through getting values back and forth between kernels, but let's call that a separate issue.
