### ISSUE TITLE
Provide IPython script magics

### ISSUE THREAD

**Issue by jcb91** [Calysto/metakernel#125]
I find the `%%shell` magic frustrating because of its persistent connection - my input is frequently out of step with output captured form the persistent shell process. I also missed the various script cell magics like `%%bash` which are provided by the core ipython implementation at https://github.com/ipython/ipython/blob/6bf8bd1f5cf6a35a805b74985b3cce6559d59b26/IPython/core/magics/script.py. It seems that magic handling is significantly different in IPython core vs metakernel, so I had to create a wrapper class to adapt the core-provided class.

I've made an implementation for my own use, and wondered whether it's something you might consider adding to metakernel - see my gist at https://gist.github.com/jcb91/28999015f787ddffa8d3c11ecda8ebe8.

Any thoughts?

**Comment by dsblank** [comment]
Sounds interesting... can you provide some details about how to use this, which magics could work, and which ones wouldn't? Why is the persistent connection to shell a problem?

**Comment by jcb91** [comment]
> Why is the persistent connection to shell a problem?

Well essentially, the output from shell commands got out of step with the input. So, I'd execute one shell command, get no output, run another, get the output from the previous command, and so on. However, I can't seem to reproduce it easily now, so maybe I hit something pretty rare which won't bother me again. In the process of trying to reproduce it though, I discovered another issue, which is that syntax errors in shell calls can result in 

1. the shell hanging, try e.g.

       !pwd '

2. the shell terminating (I think?), resulting in all subsequent `%%shell` calls failing. Try, e.g.
       
       !sleep(1)

   This could perhaps be fixed by some more error checking & then restarting a finished shell? Not too sure.

I can't say my wrapped `%%bash` handles those too perfectly either (for some reason, stderr from bash doesn't make it back to the kernel), but it does at least leave the kernel in a responsive state & allow for subsequent calls to a bash process.

> can you provide some details about how to use this, which magics could work, and which ones wouldn't?

Well, the file in the gist I just use by placing it in the metakernel magics path, in the directory `~/.ipython/metakernel/magics/`. Then it makes available `%%bash` and the like. For other magics which could work/couldn't work, it seem to me to be mainly down to what (if any) use is made of the kernel's `shell` attribute, which metakernels don't by default provide, but which some of the core ipython magics use for things like passing variables back from magics into the kernel. For example, the core script magics can be run as background processes, and their python input/output objects assigned to kernel-namespace variables - see [IPython/core/magics/script.py#L190-L196](https://github.com/ipython/ipython/blob/master/IPython/core/magics/script.py#L190-L196) for details. In most cases, this kind of thing doesn't make sense for metakernels, in others, a slightly fuller port as opposed to just a wrapper might allow the original functionality to be reproduced, I haven't studied this in detail.

One other benefit of `%%bash` over `%%shell` is the notebook frontend highlighting - you get correct syntax highlighting 😄

**Comment by blink1073** [comment]
My two cents is that `metakernel` is meant to be a true multi-kernel environment, so a `%%bash` magic should actually be calling a `%%bash` kernel.  I have recently fixed some logic errors in our `%%shell` magic that should improve the experience.  Note that our `%%shell` magic accommodates incremental output, while the `IPython` version uses `Popen.communicate()` to get the result after execution.  Incremental output would mean sacrificing the `err` output that the IPython shell magics provide.


I think we can take few things away though: 

- Our `%%shell` magic should allow setting the return value to the kernel namespace using [set_variable](https://github.com/Calysto/metakernel/blob/78fe391f27e5b3ee6063f0707b361afc90b7cc41/metakernel/_metakernel.py#L189).  
- We could add a `%%script` magic that has all of the options in the `IPython` magic except `err`, and uses [spawn](https://github.com/Calysto/metakernel/blob/78fe391f27e5b3ee6063f0707b361afc90b7cc41/metakernel/pexpect.py#L15) to provide the incremental output.
- We should add specific `%%bash`, `%%sh`, and `%%cmd` magics to be more explicit, and allow highlighting to work in the notebook.

**Comment by blink1073** [comment]
I updated the above content (for those reading email).

**Comment by dsblank** [comment]
Thanks @jcb91 for further explaining your motivations. I agree with the philosophy that @blink1073 describes for metakernel. We have standard APIs for starting, and communicating, with any metakernel-based language. See %kernel, %%kx, %parallel, %%px, and others.

(As a complete aside, I have the prototype of a kernel that provides a bash-like language in a cross-platform manner, written in Python. It isn't a complete rewrite of bash in Python, of course, but does allow some common bash/shell idioms on Windows. Powerusers would hate it because it leaves out so much.)

**Comment by jcb91** [comment]
> My two cents is that metakernel is meant to be a true multi-kernel environment, so a %%bash magic should actually be calling a %%bash kernel.

Ok, I can see what you mean, but given that

> We have standard APIs for starting, and communicating, with any metakernel-based language. See `%kernel`, `%%kx`, `%parallel`, `%%px`, and others.

it might even be considered superfluous, I guess. This sounds like perhaps a case where what I want (my metakernel to mirror the ipykernel functionality I'm familiar with) is not really what everybody wants, and as such I should probably keep my implementation as a user-defined magic as I've already done?

> Note that our `%%shell` magic accommodates incremental output, while the `IPython` version uses `Popen.communicate()` to get the result after execution. Incremental output would mean sacrificing the `err` output that the IPython shell magics provide.

Yes, they strike me as conceptually different use-cases. If anything, I think I'd prefer this to be configurable from an argument, similar to the IPython implementation's `bg` arg. I finally re-discovered what was causing me problems with the incremental outputs, and it was attempting to run `cmd` through the shell magic (which picks up & uses my cygwin bash shell rather than the windows-native cmd). I'm unsure why this was a problem, but it resulted in the output looking like it was returned from different commands, or even different cells. I suppose it could be mitigated by either making which shell gets used by `%%shell` configurable somehow, or by providing separate magics for other shells. I usually prefer bash, but occasionally want to do things in cmd like its builtin `start`.

> I have recently fixed some logic errors in our `%%shell` magic that should improve the experience.

Ok, I'm using a conda-forge package, so I'll install the latest master for this/these, I guess.

> As a complete aside, I have the prototype of a kernel that provides a bash-like language in a cross-platform manner, written in Python

neat!

Thanks both for your thoughtful responses 😃

**Comment by dsblank** [comment]
I don't think that there is anything to do here. Closing for now.
