### ISSUE TITLE
Provide mechanism to only register certain magics

### ISSUE THREAD

**Issue by virtuald** [Calysto/metakernel#126]
I'm contemplating taking an existing CLI application and making it work in an jupyter notebook environment. While some of the magics are nice, others don't make sense for my environment and it'd be nice if I could only enable the ones that make sense.

**Comment by dsblank** [comment]
That makes sense. Perhaps a config list that can be specified by the kernel, but overridden by users.

**Comment by virtuald** [comment]
For now, my workaround is this:

```python
class _MetaKernel(MetaKernel):
    
    def register_magics(self, magic_klass):
        MetaKernel.register_magics(self, magic_klass)
        
        if hasattr(self, 'allowed_line_magics'):
            self.line_magics = {k: v for k, v in self.line_magics.items() if k in self.allowed_line_magics}
        
        if hasattr(self, 'allowed_cell_magics'):
            self.cell_magics = {k: v for k, v in self.cell_magics.items() if k in self.allowed_cell_magics}
```

**Comment by dsblank** [comment]
That is a good start.

**Comment by blink1073** [comment]
Sounds reasonable to me.

**Comment by blink1073** [comment]
I don't see a good way to bake this into core, I'm going to close as addressed.
