### ISSUE TITLE
Weird extra tag 'v'

### ISSUE THREAD

**Issue by QuLogic** [Calysto/metakernel#133]
If you check the [older releases](https://github.com/Calysto/metakernel/releases?after=v0.11.5), there's a tag named `v`. Based on the other tags and the commit, I think this should actually be `v0.10.4`, and `v` should be deleted.

**Comment by blink1073** [comment]
Ha, thanks!  Deleted.

**Comment by QuLogic** [comment]
I don't know if you also want to re-add `v0.10.4` as well...

**Comment by blink1073** [comment]
Yep, done.
