### ISSUE TITLE
PTY remains open after terminating

### ISSUE THREAD

**Issue by AetherLorde** [Calysto/metakernel#140]
In my code I am spawning tons of oct2py instances, as I want clean variables in each, and exiting them when I am done. I know that I could just clear the variables that I need before each subsequent call, but I figured since I tracked this down I would go ahead an write it up. I may try to fix this on my local, but I have had problems with pip install -E in the past unfortunately. 

The problem is that when I call exit on my Oct2Py object, the pty associated with it is not closed. I believe this is because the terminate method of the underlying ptyprocess used by the REPLWrapper is the only method being called, and it doesn't seem to close the file descriptors for some reason. There is a close method on the pexpect ptyprocess that underlies it, and I think all we need to do is also call the close method when terminating the replwrapper. Please correct me if I am misunderstanding something. I am including the files and locations I traced this through at the end of this issue. Thanks for all the work you are doing with this stuff and sorry to open so many issues! 

# Potential ways to recreate:

- enter python repl
- import metakernel
- spawn some processes (in my case using the same args the octave_kernel uses, from 
https://github.com/Calysto/octave_kernel/blob/7399120bfbeaeccf02b30b3a6b68aa7928b4170d/octave_kernel/kernel.py#L351
- terminate them and note that that the number of ptys for the system remains unchanged
- now call close on the child object of the REPLWrapper, and note that the pty and its fd are closed 

# Files and calls
- https://github.com/blink1073/oct2py/blob/c188b719dbefe4a23b214f19dacbca712fc07fa8/oct2py/core.py#L507
- https://github.com/Calysto/octave_kernel/blob/7399120bfbeaeccf02b30b3a6b68aa7928b4170d/octave_kernel/kernel.py#L144
- https://github.com/Calysto/octave_kernel/blob/7399120bfbeaeccf02b30b3a6b68aa7928b4170d/octave_kernel/kernel.py#L351
- https://github.com/Calysto/metakernel/blob/e7a8d817e6443c80ac3f1faaed2cc096cb6572c8/metakernel/replwrap.py#L63
- https://github.com/Calysto/metakernel/blob/e7a8d817e6443c80ac3f1faaed2cc096cb6572c8/metakernel/replwrap.py#L194
- https://github.com/blink1073/oct2py/blob/c188b719dbefe4a23b214f19dacbca712fc07fa8/oct2py/core.py#L100
- https://github.com/pexpect/pexpect/blob/b36c03315fcf9bec711f79098b2fa31dfd264c76/pexpect/pty_spawn.py#L590
- the pty_spawn does not attempt to call close on its underlying ptyprocess, might raise issue there, but they would
- 	probably respond by asking us to just close both their close and terminate methods
- might be easier if we just call close in addition to terminate to actively close the fds associated with the ptyprocess 
- https://github.com/pexpect/pexpect/blob/b36c03315fcf9bec711f79098b2fa31dfd264c76/pexpect/pty_spawn.py#L311

**Comment by blink1073** [comment]
It looks like we should be calling `kill(signal.SIGTERM)` if no `pty` and (`terminate`, `close`) if there is a `pty`.

**Comment by blink1073** [comment]
Fixed upstream, by you!  Thanks!
