### ISSUE TITLE
Calysto Processing example not working,

### ISSUE THREAD

**Issue by misolietavec** [Calysto/metakernel#142]
because of issue 

ImportError: No module named 'metakernel.utils.kernel' in calysto_processing repository.

I made a comment about this issue, which, I suppose, can be helpful in proper update of setup.py file for calysto_processing module.  

I am writing here, because in calysto_processing repository there are stalled issues; nonetheless, I think that module to be highly useful.

**Comment by SLEEP-MAN** [comment]
Note: metakernel==0.12.6 is the latest version of metakernel compatible with Calysto Processing

**Comment by dsblank** [comment]
This is a Calysto Processing error, and should be handled in that repo. Thanks for reporting there!
