### ISSUE TITLE
In order to install python metakernel, pip command must be ended by --upgrade parameter instead of --update (as it is incorrectly written in README)

### ISSUE THREAD

**Issue by q2dg** [Calysto/metakernel#150]
Thanks

PD: Is it necessary the command _python metakernel_python install_ ?? In my system it gives "File not found" but when I open a Notebook this kernel is recognized

**Comment by dsblank** [comment]
Thanks; fixed. 

The command is `python -m metakernel_python install` (use python, or python3 as needed).
