### ISSUE TITLE
Will you merge fish shell kernel?

### ISSUE THREAD

**Issue by slavaGanzin** [Calysto/metakernel#158]
Hello, I want to create fish kernel based on metakernel. And I think it would be overkkilll to create separate repo.
So, will you merge fish kernel?

**Comment by dsblank** [comment]
Do you have a Pull Request?

**Comment by slavaGanzin** [comment]
@dsblank I'll make a PR if I find a time to implement this.

**Comment by dsblank** [comment]
Ok, thanks! And sorry it took so long to respond!
