### ISSUE TITLE
trouble when installing

### ISSUE THREAD

**Issue by parmentelat** [Calysto/metakernel#185]
this is on macos
recently I got my python/jupyter install very mixed up and decided to restart from scratch

despite of that - or maybe because of that - what I'm seeing now is this

```
$ python -m metakernel_bash install
Installed kernelspec python3 in /usr/local/share/jupyter/kernels/python3
$ cat /usr/local/share/jupyter/kernels/python3/kernel.json
{
 "argv": [
  "/usr/local/opt/python/bin/python3.7",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

I can't seem to get metakernel_bash to appear in

```
$ jupyter kernelspec list
Available kernels:
  bash       /Users/tparment/Library/Jupyter/kernels/bash
  python3    /usr/local/share/jupyter/kernels/python3
```

where bash is the kernel that somes from the alternative `bash_kernel` 

a couple weeks back I had had no problem having the 3 kernels coexisting in my jupyter environment

thanks for any hint that would let me troubleshoot that

**Comment by blink1073** [comment]
Hi @parmentelat, had you installed metakernel_bash from a git checkout?  If so, what command did you use to install it, and what does `git describe` give in that checkout?

**Comment by parmentelat** [comment]
hey @blink1073 

no I did the initial installation with plain `pip` 

```
$ pip install metakernel-bash
<snip>
$ pip freeze | grep metakernel
metakernel==0.23.0
metakernel-bash==0.11.3
```

**Comment by blink1073** [comment]
Oh wow, I didn't realize we had released metakernel_bash.  The last release was 4 years ago.  I'm going to promote it to its own repo and give it a proper release.

**Comment by blink1073** [comment]
The plot thickens.  I forgot I had created `calysto_bash` as a separate repo already.  Please try with `pip install calysto_bash`.

**Comment by parmentelat** [comment]
this works better:

```
$ pip install calysto_bash
Collecting calysto_bash
<snip>
Successfully installed calysto-bash-0.2.1
$ jupyter kernelspec list
Available kernels:
  bash            /Users/tparment/Library/Jupyter/kernels/bash
  calysto_bash    /usr/local/share/jupyter/kernels/calysto_bash
  python3         /usr/local/share/jupyter/kernels/python3
```

so; I guess I'm all good - provided that `calysto_bash` is a new name for the same thing ?

----
it's funny though because the way I did it earlier with `metakernel_bash` is working in another environment - at least it was working when I rebuilt a docker image based on top of  `jupyter/minimal-notebook` something like 2 days ago
but, no big deal in any case ..

---
anyways, thanks for your help :)

**Comment by blink1073** [comment]
Yeah I had the same weird issue with `metakernel_bash` installing as a `python3` kernel as well.  `calysto_bash` will henceforth be the supported version :wink:.  cf #186.  
Note there is still a separate [bash_kernel](https://github.com/takluyver/bash_kernel) that does not include magics.

Cheers!
