### ISSUE TITLE
Allow ipywidgets to work with metakernel magics

### ISSUE THREAD

**Issue by joequant** [Calysto/metakernel#207]
I'm working on a root kernel that is based on metakernel.  I would like to use python magics to create ipywidgets which can then interface with the metakernel kernel, but it appears that metakernel doesn't have that functionality.  Would be interested to see what needs to be done so that ipywidgets work.

**Comment by joequant** [comment]
https://github.com/Calysto/metakernel/issues/207

**Comment by dsblank** [comment]
That did work at one point I believe. Probably just needs to be updated to match the current ipywidget internals.

**Comment by joequant** [comment]
Cool.  Do you have any suggestion about where to look, and any information about when/what might have broke?  I noticed in kernelspy that it's not sending over display_data messages.

**Comment by blink1073** [comment]
I have not tried to use `ipywidgets` with a `metakernel`, but I would look at [`lazy_import_handle_comm_opened`](https://github.com/Calysto/metakernel/blob/f16faf5ff4410ef0c52dff45c64249c72db52197/metakernel/_metakernel.py#L69).  You may also need to add a [`displayhook`](https://github.com/ipython/ipykernel/blob/f0b004010c606b19321b13386fccf0dcfd964c83/ipykernel/ipkernel.py#L70) to capture the display messages.

**Comment by joequant** [comment]
There's code in _metakernel.py that dispatches Widgets, but it's not working.  Let me see why.

**Comment by joequant** [comment]
This patch will cause the widgets to display.

[_metakernel.py.diff.txt](https://github.com/Calysto/metakernel/files/5090900/_metakernel.py.diff.txt)

**Comment by dsblank** [comment]
@joequant Great! Can you make a PR?
