### ISSUE TITLE
Python magics evaluate doesn't match comments

### ISSUE THREAD

**Issue by joequant** [Calysto/metakernel#208]
The comments in python magics says

            %%python -e                                                         
            retval = "'(this is code in the kernel language)"                   
                                                                                
            %%python -e                                                         
            "'(this is code in the kernel language)"

However, the code sets the evaluate to none if retval is not availabe

                self.code = str(self.env["retval"]) if ("retval" in self.env and
                                                        self.env["retval"] != None) else ""

Should it be?

                self.retval = self.eval(self.code)
                self.code = str(self.env["retval"]) if ("retval" in self.env and
                                                        self.env["retval"] != None) else str(self.retval)
??

**Comment by blink1073** [comment]
That sounds right

**Comment by joequant** [comment]
Fixed in 0.25.0

**Comment by joequant** [comment]
Fixed in 0.25.0
