### ISSUE TITLE
Add %install_kernel magic

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#25]
It would be very handy if there were a known list of kernels that could be listed and easily installed. These kernels would go into the user's kernel folder. To list, we could have a list in the jupyter_kernel repository, but you could also just add by name, via pip.

Could work like this:

```
%install_kernel [OPTIONS] pip-name ...
%install_kernal octave_kernel
%install_kernal octave_kernel prolog_kernel
%install_kernel --list
%install_kernel --info pip-name
%install_kernel --host http://url/of/kernels name_of_kernel
```
A list of kernels at a host might be a json file:
```json
{'octave': {'name': Octave', 'description': ..., 'pip-name':}, ...}}
```
Is this out of scope for jupyter_kernel?

**Comment by dsblank** [comment]
Also in progress:

https://github.com/blink1073/metakernel/blob/master/metakernel/magics/install_magic.py

The idea here is that there would be a list (somewhere) of known extensions/nbextensions/settings so that a user only need to know the name of the "package" and it woul be installed. 

Currently, this will download using pip, and edit a user's custom.js. This is really a rough draft, but I needed this for a demo. We can revise, or remove if it doesn't scale up.

**Comment by dsblank** [comment]
Check out this extension:

https://www.youtube.com/watch?v=h9DEfxZSz2M

It would be good to build things like this for jupyter systems overall.

**Comment by blink1073** [comment]
Very cool, who doesn't love writing JavaScript?  :smile:

**Comment by dsblank** [comment]
I think that this is now handled by the Jupyter system overall. Closing.
