### ISSUE TITLE
tar-ball on pypi is missing license and some other files

### ISSUE THREAD

**Issue by arunpersaud** [Calysto/metakernel#253]
Hi

I'm just packaging metakernel for the opensuse linux distribution and noticed that CONTRIBUTORS.rst, CHANGELOG.md, RELEASE.md, and LICENSE.txt have gone missing from the tar-ball. Any chance to get them back in the next release?

Thanks

Arun

**Comment by blink1073** [comment]
Thanks for the heads up @arunpersaud, I'll make a fix and release early this week.
