### ISSUE TITLE
_ipython_display_ function displays incorrectly

### ISSUE THREAD

**Issue by WheatMaThink** [Calysto/metakernel#267]
This is the first time to use metakernel, please help, thank you.

html is not displayed correctly

```python 
import uuid
from IPython.display import display_html,HTML, display

class FlotPlot(object):
    def __init__(self):
        self.uuid = str(uuid.uuid4())
    
    def _ipython_display_(self):
        display_html('<h3>Title one</h3>',raw=False)
        display(HTML('<h3>Title two</h3>'))

```
![image](https://github.com/Calysto/metakernel/assets/8164911/7d134d53-dd26-4c13-bd0b-d088f30100d7)

Regards

**Comment by dsblank** [comment]
What kernel are you using?

**Comment by WheatMaThink** [comment]
@dsblank 

The following is environmental information：

Metakernel  v0.30.0
python -m jupyter lab --version 4.0.5


The following is the fix patch：

file _metakernel.py 

451 lines
'''python

              if not silent:  # silent=False 
                    if Widget and isinstance(retval, Widget):
                        self.Display(retval)
                        return

                    if hasattr(retval, "_ipython_display_"):  # fix patch
                        self.log.debug('post_execute  _ipython_display_')
                        self.Display(retval)  # 需要修改Display函数
                        return

                    self.send_response(self.iopub_socket, 'execute_result', content)
'''
639 lines
'''python

                self.send_response(
                    self.iopub_socket,
                    'display_data',
                    content
                )
            elif hasattr(item, "_ipython_display_"):
                self.log.debug('Display _ipython_display_')
                try:
                    self.log.info(item)
                    item._ipython_display_()  # 成功
                except Exception as e:
                    self.Error(e)
                    return

            else:
                self.log.debug('Display Data')
'''

**Comment by dsblank** [comment]
Thank you @WheatMaThink ! Do you know how to make a Pull Request?

**Comment by WheatMaThink** [comment]
@dsblank 

I haven't pulled the code on Github yet, I will learn how to operate it later. If the functionality is complete, please help update this time. Thank you.
