### ISSUE TITLE
Fix Upstream Problems

### ISSUE THREAD

**Issue by blink1073** [Calysto/metakernel#28]
This is meant as a placeholder for problems we notice upstream:
Note: these have only been observed when using the qtconsole:

- When the kernel language is python, the following is executed at startup:
    `try:\n    _usage\nexcept:\n    from IPython.core import usage as _usage\n  get_ipython().register_magic_function(_usage.page_guiref, 'line', 'guiref')\n    del _usage`
- At startup, `do_inspect` is called for the banner and the startup execute code.
- When executing code, `do_inspect` is called six times and `do_execute` is called twice
- `do_complete` is not always called when the TAB key is pressed (based on python syntax)
- The shell does not respect the `"codemirror_mode"` of the kernel

**Comment by dsblank** [comment]
I think all issues (even the is_complete) has been addressed upstream.
