### ISSUE TITLE
Create a MetaKernel github organization?

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#59]
Jupyter is planned as an release candidate/alpha release in about 2 weeks. What do you think about creating a MetaKernel organization and putting metakernel under that? That way, it isn't tied to a particular user and provide a long-term org independent of current developers. Also gives us a better project URL.

**Comment by blink1073** [comment]
Sounds good to me.

**Comment by dsblank** [comment]
Bummer... there is a github user named @metakernel but they are inactive. Wonder if they would be willing to rename their account?

**Comment by dsblank** [comment]
Or name it MetaMetaKernel as a bit of a joke/workaround.

**Comment by blink1073** [comment]
I wonder if Jupyter would take us as a sub-repo.

**Comment by dsblank** [comment]
I think we would have to have the same contributors then wouldn't we?

**Comment by blink1073** [comment]
Well, the Jupyter admins would have rights to all, but they could explicitly add us to that one repo.

**Comment by blink1073** [comment]
@takluyver, how would you feel about moving this repo to the Jupyter umbrella?

**Comment by dsblank** [comment]
@blink1073 I've been thinking that it may be nice to have a set of repos under a non-official umbrella. That gives a bit more flexibility. In addition to just kernels, I think cross-kernel support for nbextensions, extensions, and perhaps entire apps. Perhaps something like MetaProject, for now?

**Comment by blink1073** [comment]
How about MetaJupyter?

**Comment by dsblank** [comment]
I don't think the Jupyter people will like that :( They already asked us to change from jupyter_kernel, if you recall.

**Comment by blink1073** [comment]
To be fair that was a confusing name.  I don't see a problem with MetaJupyter.  Its an organization *about* Jupyter and *for* Jupyter, but is *not* Jupyter.

**Comment by blink1073** [comment]
My next favorite would be TotesMetaJupyter.

**Comment by dsblank** [comment]
What does TotesMetaJupyter mean? I think the Jupyter folks think of "Jupyter" as their brand, and it would be confusing for others to use if. But you can ask. I can't come up with anything other than MetaProject... unless we come up with our own branding...

**Comment by blink1073** [comment]
"Totes" is what the kids say instead of "Totally"  :smile:  
What about your existing "Calysto" umbrella?

**Comment by dsblank** [comment]
Sure... we can put it under Calysto. I like that!

**Comment by takluyver** [comment]
Yeah, I think we'd rather you didn't use the name 'MetaJupyter' - that implies something with a more official relationship to Jupyter (like Stackoverflow and Metastackoverflow). Thanks!

**Comment by dsblank** [comment]
Ok, I think that this is a good idea. You can "transfer ownership" under settings for the repo. Just invited you to be an owner. Keith O'Hara is also an admin there---he is a prof at Bard College in upstate NY.

**Comment by blink1073** [comment]
@dsblank, I believe you'll have to log in to Travis and Coveralls to enable them, since you are the "owner".

**Comment by blink1073** [comment]
I updated the Readme both in the repo and on PyPi.

**Comment by dsblank** [comment]
I think that they are both enabled now... not positive though...

**Comment by blink1073** [comment]
I just pushed a change, let's see what it does...

**Comment by dsblank** [comment]
Travis is running so that looks ok.

**Comment by blink1073** [comment]
And coveralls made it too, sweetness.

**Comment by blink1073** [comment]
Close this one?

**Comment by dsblank** [comment]
Yep, thanks! Now, we can be organized in our new organization! Totes :) (I had to ask my teenage daughter to confirm your cred on "totes"...)
