### ISSUE TITLE
Allow magic positional arguments

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#66]
Currently you can't do this:

```
%plot inline
```

but only:

```
%plot -b inline
```
What would it take to be able to use positional arguments too?

**Comment by blink1073** [comment]
Yeah, I had this on my todo list, thanks for formalizing it :smile:

**Comment by blink1073** [comment]
Closed by 2e6bcd7.

**Comment by dsblank** [comment]
You're a genius and a scholar!
