### ISSUE TITLE
API for using a MetaKernel-based kernel as a cell magic from IPython

### ISSUE THREAD

**Issue by dsblank** [Calysto/metakernel#67]
Here is the code currently required to use a MetaKernel-based kernel (in this example, Calysto Processing) as a cell magic from inside IPython:

```python
from calysto.language.processing.kernel import ProcessingKernel

from IPython import get_ipython
from IPython.core.magic import register_cell_magic
from IPython.display import display

kernel = ProcessingKernel()   ## make a global Kernel
ip = get_ipython()          ## need access to IPython session:
kernel.session = ip.parent.session
kernel.Display = display        ## use IPython's display, not MetaKernel's

@register_cell_magic
def processing(line, cell):
    "my cell magic"
    result = kernel.do_execute_direct(cell)
    return result
```

Then you can:

```
%%processing

void draw() {
    ellipse(50, 50, 10, 10);
}
```

It would be good to make this an official API. Should work with any MetaKernel-based kernel, yes?

**Comment by blink1073** [comment]
It seems like we should provide a helper function that takes a `MetaKernel` class as an argument and creates the cell magic.  Then the kernel provider could use this function in `load_ipython_extension` to provide the extension point.

**Comment by dsblank** [comment]
Yes, that is a good idea. It was more specific than what I was thinking, but would be good to hide the details and encourage this functionality with all metakernel kernels.

**Comment by dsblank** [comment]
For the moment, I'll just make a minimal change. We already had the idea of a metakernel being a subkernel. Added ability for other kernel types to be the main kernel, and specifically to allow IPython main kernels: 

```python
from calysto.language.processing.kernel import ProcessingKernel
from IPython.core.magic import register_cell_magic

kernel = ProcessingKernel()   ## make a global Kernel
kernel.makeSubkernelToIPython()

@register_cell_magic
def processing(line, cell):
    result = kernel.do_execute_direct(cell)
    return result
```

**Comment by blink1073** [comment]
Looks good for now, I'll look at wrapping it at a higher level.

**Comment by blink1073** [comment]
How about a generic kernel loader (by name)

```python
%loadext metakernel.metakernel_start
%metakernel_start processing
%%processing
....
```

**Comment by blink1073** [comment]
It seems like something that should exist within IPython come to think of it.  The ability to load another kernel and call it by name as a cell.

**Comment by dsblank** [comment]
We could port the `%kernel` magic over to IPython. That should be easy. It would be nice for that kernel magic to have a shortcut magic (`%%processing`) like you describe, too.

**Comment by blink1073** [comment]
Sounds like a plan.

**Comment by dsblank** [comment]
Just added `metakernel.register_ipython_magics(...)` that will register those magics with a `register_ipython_magics` function to add this magic as a IPython magic. So far, have just added:

- [x] download
- [x] tutor

To use from ipython:
```python
from metakernel import register_ipython_magics
register_ipython_magics()
```

or
```python
from metakernel import register_ipython_magics
register_ipython_magics("download", "tutor", ...)
```

**Comment by blink1073** [comment]
Looks good to me, nice work!

**Comment by dsblank** [comment]
The only remaining issue is to implement the %kernel code for use in IPython. Someone can open up an issue if they are interested in that.
