### ISSUE TITLE
 [Errno 2] No such file or directory: '/e2e/jupyter-venv/lib64/python3.4/site-packages/metakernel/images/logo-64x64.png'

### ISSUE THREAD

**Issue by marmalodak** [Calysto/metakernel#69]
How do I work around this?

    ...
      Running setup.py install for ipdb

        Fixing build/lib/ipdb/__main__.py build/lib/ipdb/__init__.py
        Skipping implicit fixer: buffer
        Skipping implicit fixer: idioms
        Skipping implicit fixer: set_literal
        Skipping implicit fixer: ws_comma
        Fixing build/lib/ipdb/__main__.py build/lib/ipdb/__init__.py
        Skipping implicit fixer: buffer
        Skipping implicit fixer: idioms
        Skipping implicit fixer: set_literal
        Skipping implicit fixer: ws_comma
        Installing ipdb3 script to /e2e/jupyter-venv/bin
      Running setup.py install for metakernel-python

        error: [Errno 2] No such file or directory: '/e2e/jupyter-venv/lib64/python3.4/site-packages/metakernel/images/logo-64x64.png'
        Complete output from command /e2e/jupyter-venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo8avkmz/metakernel-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jtwll3hi-record/install-record.txt --single-version-externally-managed --compile --install-headers /e2e/jupyter-venv/include/site/python3.4:
        running install

    running build

    running build_py

    creating build

    creating build/lib

    copying metakernel_python.py -> build/lib

    running install_lib

    copying build/lib/metakernel_python.py -> /e2e/jupyter-venv/lib/python3.4/site-packages

    byte-compiling /e2e/jupyter-venv/lib/python3.4/site-packages/metakernel_python.py to metakernel_python.cpython-34.pyc

    running install_egg_info

    running egg_info

    creating metakernel_python.egg-info

    writing top-level names to metakernel_python.egg-info/top_level.txt

    writing requirements to metakernel_python.egg-info/requires.txt

    writing metakernel_python.egg-info/PKG-INFO

    writing dependency_links to metakernel_python.egg-info/dependency_links.txt

    writing manifest file 'metakernel_python.egg-info/SOURCES.txt'

    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'metakernel_python.egg-info/SOURCES.txt'

    writing manifest file 'metakernel_python.egg-info/SOURCES.txt'

    Copying metakernel_python.egg-info to /e2e/jupyter-venv/lib/python3.4/site-packages/metakernel_python-0.7.0-py3.4.egg-info

    writing list of installed files to '/tmp/pip-jtwll3hi-record/install-record.txt'

    error: [Errno 2] No such file or directory: '/e2e/jupyter-venv/lib64/python3.4/site-packages/metakernel/images/logo-64x64.png'

    ----------------------------------------
    Cleaning up...
    Command /e2e/jupyter-venv/bin/python3.4 -c "import setuptools, tokenize;__file__='/tmp/pip-build-lo8avkmz/metakernel-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jtwll3hi-record/install-record.txt --single-version-externally-managed --compile --install-headers /e2e/jupyter-venv/include/site/python3.4 failed with error code 1 in /tmp/pip-build-lo8avkmz/metakernel-python
    Storing debug log for failure in /root/.pip/pip.log

**Comment by blink1073** [comment]
ping @dsblank.

@marmalodak, you could try commenting [this](https://github.com/Calysto/metakernel/blob/master/setup.py#L37) out as a workaround.

**Comment by dsblank** [comment]
I hadn't tested with setuptools. I usually use:

```
pip -e install
```
If @blink1073 's suggestion doesn't work, try:

```
cp MANIFEST.in MANIFEST
```

**Comment by dsblank** [comment]
I have tested with: `pip install metakernel`. If you have a PR that will allow other installation methods to also work, we will consider, and please re-open.
