### ISSUE TITLE
bash() in replwrap.py expects bash prompt to end with $ or #?

### ISSUE THREAD

**Issue by nelsonuhan** [Calysto/metakernel#92]
I was playing around with a Jupyter Notebook with the metakernel_bash kernel, and I noticed that the kernel took an unusually long time to load, and the notebook wouldn't work as expected (i.e., not like a bash prompt). In the log, I was getting an error message having to do with shell_magic.py. 

After some digging around, it seems that bash() in replwrap.py expects my bash prompt to end with $ or #. I had a custom prompt that didn't end in either of those characters. Changing my custom prompt to end with $ solved the problem.

I'm not sure what's the best way to solve this - just thought you should know.

**Comment by blink1073** [comment]
Yes, I'm not sure of a clean way to handle custom prompts.
