### ISSUE TITLE
Enabling graphics for the metakernel_bash

### ISSUE THREAD

**Issue by mjbright** [Calysto/metakernel#95]
I'm looking at ways of enabling graphics for the bash kernel.
I think there could be some nice use cases of having a mainly bash notebook with just the necessary to supplement with graphics.

For the moment I have GraphViz enabled via pydot (actually pydotplus on Windows) in this fork
    https://github.com/mjbright/metakernel
Here's a simple example of displaying a file hierarchy
![metakernelbash_graphviz](https://cloud.githubusercontent.com/assets/1880109/15122562/0b7dd5e2-1620-11e6-8361-8829008a0ae8.PNG)

Sorry, I've not made any pull requests, I really need to learn to use git properly !

Nevertheless, I think there are some interesting ideas in there
- integration of image display function (essentially copied from takluyver/bash_kernel)
- integration of a pydot function to invoke graphviz
- sourcing of a metakernelrc allowing the user to define "higher-level" functions

But I'd really like to enable richer graphics in various ways.
1. I'd like to be able to do the equivalent of
      %matplotlib inline
   within a %%python cell.
   
   This could be using matplotlib (would be nice as it's common) or would it be possible to integrate
   inline some other Python graphics lib?
2. Or invoke some D3.js for example in a %%javascript cell, or call out to a Lightning server.  

However, it seems to me that all these use cases beg the question of how to pass data from the bash cells to a %%python or %%javascript cell, I guess writing/reading a temporary file would be the only way, right?

I'll probably try a few of these things, any suggestions would be appreciated.

**Comment by dsblank** [comment]
Some good ideas here, but two issues:

1. the bash-specific ones should be broken up into PRs, each to target a single issue
2. it seems that the common parts of the imagine and dot files could be abstracted into a general: extension/display-type framework.

It seems like you have made a lot of useful improvements in general for Windows, but if we can't get them as specific PRs, they won't make it into the common codebase.

If there were a common framework, then any kernel could put a file in a special directory, and metakernel would display it. That would include dot files, but also html, and any other type that IPython.display can display.

**Comment by mjbright** [comment]
Hi Doug,

Yes, I do need to break my code into separate git branches and so separate
PRs (I need to learn to use git properly !).
The very little Windows specific code should be a separate branch.

I'm sure that a more general framework could be created, but there are some
basic issues of what (and how) can and can't be done from the notebook
which are unclear to me (communication between cells/cell types, access to
display capabilities), whence my questions in the issue.

In particular, it's unclear to me how a metakernel such as bash can have
access to IPython.display.
I single out bash because it seems that it's the kernel which wouild have
the "weakest" Python integration.

Thanks for your comments,
Mike.

**Comment by dsblank** [comment]
Closing for now. Perhaps a future PR can target a general use.
