### ISSUE TITLE
source install of metakernel puts its data (logo files) to /usr/metakernel

### ISSUE THREAD

**Issue by anntzer** [Calysto/metakernel#96]
Try e.g. `sudo pip install --upgrade .` from the source folder.  Note that the files dumped to the non-standard `/usr/metakernel` location don't even get removed upon `sudo pip uninstall metakernel`.

`package_data` is preferred to `data_files` nowadays (https://github.com/pypa/pip/issues/2874#issuecomment-109444845), it should be possible to install the logos within the package folder instead.

Wheels also install to the non-standard `/usr/metakernel/`, but at least uninstall properly from there.

**Comment by dsblank** [comment]
We've have major issues trying to get the images to be installed and accessible here. 

Can you make these changes on your setup, test to see if they work, and send a PR?

**Comment by anntzer** [comment]
Now that' I'm going to mess up with `setup.py`... Would it be OK to just depend on setuptools?  Also, what's the line about `--single-version-externally-managed` about?
```
svem_flag = '--single-version-externally-managed'
if svem_flag in sys.argv:
    # Die, setuptools, die.
    sys.argv.remove(svem_flag)
```

**Comment by blink1073** [comment]
That was copied over from the original Bash Kernel I believe.  I'd suggest modeling the `setup.py` and notebook extension handling after `bqplot`.

**Comment by anntzer** [comment]
`bqplot` uses `data_files` to directly install some stuff into `$PREFIX/share/jupyter/...`, which could also be used for the kernelspec itself... perhaps not a bad idea.

**Comment by blink1073** [comment]
That's why I recommending looking at it 😉

**Comment by dsblank** [comment]
This fixed now?

**Comment by anntzer** [comment]
yes
